import {
  CAPABILITY_PROTOCOL,
  type CapabilityContract,
  type SkillBlockCapability,
} from './contracts';

const contextInput = [{ name: 'in', schema: 'pocket.context/v1', required: true }] as const;
const contextOutput = [{ name: 'out', schema: 'pocket.context/v1', required: true }] as const;

export const CAPABILITY_CATALOG: Record<SkillBlockCapability, CapabilityContract> = {
  'trigger.manual': {
    protocol: CAPABILITY_PROTOCOL,
    capability: 'trigger.manual',
    version: '1.0.0',
    stage: 'trigger',
    family: '启动条件',
    title: '手动启动',
    detail: 'Manual Trigger',
    description: '由用户明确点击后创建一次技能运行。',
    execution: 'host',
    runtime_binding: 'manual.confirm',
    provider: '宿主界面',
    inputs: [],
    outputs: [...contextOutput],
    permissions: [],
    data_policy: 'ephemeral',
    default_config: {},
  },
  'sensor.location': {
    protocol: CAPABILITY_PROTOCOL,
    capability: 'sensor.location',
    version: '1.0.0',
    stage: 'sense',
    family: '数据输入',
    title: '位置数据',
    detail: 'Location Input',
    description: '按最小权限读取坐标、精度与时间戳。',
    execution: 'browser',
    runtime_binding: 'browser.geolocation',
    provider: '手机 GPS',
    inputs: [...contextInput],
    outputs: [...contextOutput],
    permissions: ['read:location'],
    data_policy: 'ephemeral',
    default_config: { high_accuracy: true, timeout_ms: 12000 },
  },
  'sensor.health': {
    protocol: CAPABILITY_PROTOCOL,
    capability: 'sensor.health',
    version: '1.0.0',
    stage: 'sense',
    family: '数据输入',
    title: '健康摘要',
    detail: 'Readiness Input',
    description: '读取用户已确认的恢复事实，不自行诊断。',
    execution: 'local-store',
    runtime_binding: 'local.health-events',
    provider: '本机健康事件',
    inputs: [...contextInput],
    outputs: [...contextOutput],
    permissions: ['read:health_events'],
    data_policy: 'local-only',
    default_config: { lookback_hours: 24 },
  },
  'model.gemma': {
    protocol: CAPABILITY_PROTOCOL,
    capability: 'model.gemma',
    version: '1.0.0',
    stage: 'think',
    family: '处理与模型',
    title: '语义决策',
    detail: 'Gemma Processor',
    description: '通过 pocketbuddy-api 把结构化上下文转成候选动作，不直接执行副作用。',
    execution: 'pocketbuddy-api',
    runtime_binding: 'api.llm.generate',
    provider: 'Gemma / pocketbuddy-api',
    inputs: [...contextInput],
    outputs: [...contextOutput],
    permissions: ['run:model'],
    data_policy: 'ephemeral',
    default_config: { json: false, task: 'skill-canvas' },
  },
  'model.pose': {
    protocol: CAPABILITY_PROTOCOL,
    capability: 'model.pose',
    version: '1.0.0',
    stage: 'think',
    family: '处理与模型',
    title: '姿态识别',
    detail: 'Pose Processor',
    description: '从连续帧输出可复查的姿态信号，低置信度返回 unknown。',
    execution: 'browser',
    runtime_binding: 'local.pose-estimator',
    provider: '本地视觉适配器',
    inputs: [...contextInput],
    outputs: [...contextOutput],
    permissions: ['capture:camera', 'run:model'],
    data_policy: 'local-only',
    default_config: { confidence_threshold: 0.7 },
  },
  'gate.safety': {
    protocol: CAPABILITY_PROTOCOL,
    capability: 'gate.safety',
    version: '1.0.0',
    stage: 'guard',
    family: '流程控制',
    title: '安全门',
    detail: 'Safety Gate',
    description: '出现疼痛、眩晕、呼吸异常或停止指令时确定性阻断后续动作。',
    execution: 'host',
    runtime_binding: 'local.safety-gate',
    provider: '确定性规则',
    inputs: [...contextInput],
    outputs: [...contextOutput],
    permissions: [],
    data_policy: 'ephemeral',
    default_config: { stop_signals: ['pain', 'dizzy', 'breathing_abnormal', 'stop'] },
  },
  'action.voice': {
    protocol: CAPABILITY_PROTOCOL,
    capability: 'action.voice',
    version: '1.0.0',
    stage: 'act',
    family: '动作输出',
    title: '语音通知',
    detail: 'Voice Action',
    description: '把已确认的下一步通过宿主语音能力播报。',
    execution: 'browser',
    runtime_binding: 'browser.speech-synthesis',
    provider: '宿主语音',
    inputs: [...contextInput],
    outputs: [...contextOutput],
    permissions: ['notify:user'],
    data_policy: 'ephemeral',
    default_config: { lang: 'zh-CN' },
  },
  'state.skill_completed': {
    protocol: CAPABILITY_PROTOCOL,
    capability: 'state.skill_completed',
    version: '1.0.0',
    stage: 'remember',
    family: '状态与证据',
    title: '完成与证据',
    detail: 'Completion State',
    description: '先将 Graph Trace 与 Evidence 保存在本机，再只同步规范允许的 skill_completed 事实。',
    execution: 'local-store',
    runtime_binding: 'local.evidence-and-health-sync',
    provider: 'IndexedDB + pocketbuddy-api',
    inputs: [...contextInput],
    outputs: [...contextOutput],
    permissions: ['write:health_events'],
    data_policy: 'approved-fact-sync',
    default_config: { visibility: 'private' },
  },
};

export function capabilityContract(capability: SkillBlockCapability): CapabilityContract {
  return CAPABILITY_CATALOG[capability];
}
