"""initial schema

Revision ID: 72a7e8c15a6e
Revises: 
Create Date: 2026-05-29 22:30:55.457431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a7e8c15a6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.String(length=32), nullable=False),
    sa.Column('venue', sa.String(length=16), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('weekly_frequency', sa.Integer(), nullable=False),
    sa.Column('injury_risk', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('weekly_frequency >= 1 AND weekly_frequency <= 7', name='ck_assessment_weekly_frequency'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('consent_records',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('consent_type', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'consent_type')
    )
    op.create_table('permission_records',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'scope')
    )
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_plans_user_id'), ['user_id'], unique=False)

    op.create_table('training_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_entitlements',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entitlement', sa.String(length=8), nullable=False),
    sa.Column('free_quota_used', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('free_quota_used >= 0', name='ck_entitlement_quota'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('form_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('exercise', sa.String(length=32), nullable=False),
    sa.Column('is_standard', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('problem_areas', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('correction_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_reports',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('form_score', sa.Integer(), nullable=False),
    sa.Column('risk_notes', sa.JSON(), nullable=False),
    sa.Column('correction_count', sa.Integer(), nullable=False),
    sa.Column('next_focus', sa.String(), nullable=False),
    sa.Column('summary_text', sa.String(), nullable=True),
    sa.CheckConstraint('form_score >= 0 AND form_score <= 100', name='ck_report_form_score'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('set_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('exercise', sa.String(length=32), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='ck_set_difficulty'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_command_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_command_events')
    op.drop_table('set_records')
    op.drop_table('session_reports')
    op.drop_table('form_analyses')
    op.drop_table('user_entitlements')
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_sessions_started_at'))

    op.drop_table('training_sessions')
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_plans_created_at'))

    op.drop_table('training_plans')
    op.drop_table('permission_records')
    op.drop_table('consent_records')
    op.drop_table('assessments')
    # ### end Alembic commands ###
