# Lian Le Ma - one-click launcher
# What it does: detect this PC's LAN IP -> write app/.env -> start model server (web_app.py) + Expo.
# Usage: double-click start.bat, or run:
#        powershell -ExecutionPolicy Bypass -File .\start.ps1
#
# After switching WiFi, just run this script again - no manual file editing needed.

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Definition
$appDir = Join-Path $root "app"
$envFile = Join-Path $appDir ".env"
$modelPort = 4000

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "  Lian Le Ma - Launcher" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

# ---- 1. Detect LAN IP ----
function Get-LanIP {
    # Prefer Wi-Fi/WLAN, then ethernet; exclude loopback / virtual adapters (VMware/VirtualBox/WSL/Hyper-V).
    $cands = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
        Where-Object {
            $_.IPAddress -notlike "127.*" -and
            $_.IPAddress -notlike "169.254.*" -and
            $_.PrefixOrigin -ne "WellKnown"
        }
    foreach ($kw in @("Wi-Fi", "WLAN")) {
        $hit = $cands | Where-Object { $_.InterfaceAlias -match $kw } | Select-Object -First 1
        if ($hit) { return $hit.IPAddress }
    }
    $eth = $cands | Where-Object {
        $_.InterfaceAlias -notmatch "vEthernet|VMware|VirtualBox|Loopback|WSL|Hyper-V"
    } | Select-Object -First 1
    if ($eth) { return $eth.IPAddress }
    if ($cands) { return ($cands | Select-Object -First 1).IPAddress }
    return $null
}

$ip = Get-LanIP
if (-not $ip) {
    Write-Host "[WARN] Could not auto-detect LAN IP. Run 'ipconfig' and edit app/.env manually." -ForegroundColor Yellow
    $ip = Read-Host "Enter this PC's LAN IP (e.g. 192.168.1.10)"
}
$baseUrl = "http://${ip}:${modelPort}"
Write-Host "[1/3] LAN IP: $ip" -ForegroundColor Green
Write-Host "      Model server URL: $baseUrl"

# ---- 2. Write app/.env ----
$envContent = @"
# Auto-generated by start.ps1 (re-run after switching network to update).
EXPO_PUBLIC_MODEL_BASE_URL=$baseUrl
EXPO_PUBLIC_MODEL_MODE=manual
"@
Set-Content -Path $envFile -Value $envContent -Encoding ASCII
Write-Host "[2/3] Wrote $envFile" -ForegroundColor Green

# ---- 3. Start model server + Expo ----
Write-Host "[3/3] Launching model server and Expo (separate windows)..." -ForegroundColor Green

# 清除 Metro 缓存，确保手机拿到最新代码
$metroCache = Join-Path (Join-Path $appDir "node_modules") ".cache"
if (Test-Path $metroCache) {
    Remove-Item -Recurse -Force $metroCache -ErrorAction SilentlyContinue
    Write-Host "      Metro cache cleared." -ForegroundColor DarkGray
}

Start-Process powershell -ArgumentList @(
    "-NoExit", "-Command",
    "cd '$root'; Write-Host '== Model server web_app.py (port $modelPort) =='; python web_app.py"
)

Start-Sleep -Seconds 3

Start-Process powershell -ArgumentList @(
    "-NoExit", "-Command",
    "cd '$appDir'; Write-Host '== Expo dev server (cache cleared) =='; npx expo start --clear"
)

Write-Host ""
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "  Started. Next steps:" -ForegroundColor Cyan
Write-Host "  - Phone: join the SAME WiFi, scan the QR in the Expo window with Expo Go" -ForegroundColor White
Write-Host "  - PC browser: press 'w' in the Expo window, or open http://localhost:8081" -ForegroundColor White
Write-Host "  - Model URL set to: $baseUrl" -ForegroundColor White
Write-Host "  - Close the two new windows to stop the servers" -ForegroundColor White
Write-Host "==================================================" -ForegroundColor Cyan
