package art.throughtheglass.pocketearth;

import android.Manifest;
import android.content.ContentUris;
import android.database.Cursor;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Build;
import android.provider.MediaStore;
import android.util.Size;
import androidx.core.content.ContextCompat;
import com.getcapacitor.FileUtils;
import com.getcapacitor.JSArray;
import com.getcapacitor.JSObject;
import com.getcapacitor.PermissionState;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import com.getcapacitor.annotation.Permission;
import com.getcapacitor.annotation.PermissionCallback;
import java.io.File;
import java.io.FileOutputStream;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Images-only MediaStore bridge for the Photos tab.
 *
 * It deliberately does not request video access and never copies originals.
 * The only generated bytes are 320px JPEG thumbnails in app-private cache;
 * IndexedDB receives the stable MediaStore asset id and metadata.
 */
@CapacitorPlugin(
    name = "PocketPhotoLibrary",
    permissions = {
        // Android 14 requires both permissions in the same request to expose
        // the system's "selected photos" choice and its limited state.
        @Permission(strings = {
            Manifest.permission.READ_MEDIA_IMAGES,
            Manifest.permission.READ_MEDIA_VISUAL_USER_SELECTED
        }, alias = "images"),
        @Permission(strings = { Manifest.permission.READ_EXTERNAL_STORAGE }, alias = "legacyImages")
    }
)
public class PhotoLibraryPlugin extends Plugin {
    private static final int DEFAULT_LIMIT = 120;
    private static final int MAX_LIMIT = 250;
    private static final int DEFAULT_THUMBNAIL = 320;
    private final ExecutorService executor = Executors.newSingleThreadExecutor();
    private final DateTimeFormatter iso = DateTimeFormatter.ISO_OFFSET_DATE_TIME.withZone(ZoneOffset.UTC);

    @Override
    protected void handleOnDestroy() {
        executor.shutdown();
        super.handleOnDestroy();
    }

    @PluginMethod
    public void checkAuthorization(PluginCall call) {
        call.resolve(authorizationResult());
    }

    @PluginMethod
    public void requestAuthorization(PluginCall call) {
        String state = authorizationState();
        if ("authorized".equals(state) || "limited".equals(state)) {
            call.resolve(authorizationResult());
            return;
        }
        getContext().getSharedPreferences("pocket-photo-library", 0).edit().putBoolean("asked", true).apply();
        requestPermissionForAlias(Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU ? "images" : "legacyImages", call, "permissionCallback");
    }

    @PermissionCallback
    private void permissionCallback(PluginCall call) {
        call.resolve(authorizationResult());
    }

    @PluginMethod
    public void getLibrary(PluginCall call) {
        String authorization = authorizationState();
        if (!"authorized".equals(authorization) && !"limited".equals(authorization)) {
            call.reject("photo_library_permission_required");
            return;
        }
        int offset = Math.max(0, call.getInt("offset", 0));
        int limit = Math.min(MAX_LIMIT, Math.max(1, call.getInt("limit", DEFAULT_LIMIT)));
        int thumbWidth = Math.max(64, call.getInt("thumbnailWidth", DEFAULT_THUMBNAIL));
        int thumbHeight = Math.max(64, call.getInt("thumbnailHeight", DEFAULT_THUMBNAIL));
        double quality = Math.max(0.35, Math.min(0.9, call.getDouble("thumbnailQuality", 0.66)));
        executor.execute(() -> {
            try {
                JSObject result = queryImages(offset, limit, thumbWidth, thumbHeight, quality);
                getBridge().executeOnMainThread(() -> call.resolve(result));
            } catch (Exception error) {
                getBridge().executeOnMainThread(() -> call.reject(error.getMessage(), error));
            }
        });
    }

    @PluginMethod
    public void getThumbnailUrl(PluginCall call) {
        String id = call.getString("id");
        if (id == null || !id.startsWith("image:")) {
            call.reject("invalid_photo_asset_id");
            return;
        }
        int width = Math.max(64, call.getInt("width", DEFAULT_THUMBNAIL));
        int height = Math.max(64, call.getInt("height", DEFAULT_THUMBNAIL));
        double quality = Math.max(0.35, Math.min(0.9, call.getDouble("quality", 0.66)));
        executor.execute(() -> {
            try {
                long numericId = Long.parseLong(id.substring("image:".length()));
                Uri uri = ContentUris.withAppendedId(imagesUri(), numericId);
                File thumbnail = thumbnail(uri, numericId, width, height, quality);
                if (thumbnail == null) throw new IllegalStateException("photo_thumbnail_unavailable");
                JSObject result = fileObject(thumbnail);
                getBridge().executeOnMainThread(() -> call.resolve(result));
            } catch (Exception error) {
                getBridge().executeOnMainThread(() -> call.reject(error.getMessage(), error));
            }
        });
    }

    private JSObject queryImages(int offset, int limit, int thumbWidth, int thumbHeight, double quality) throws Exception {
        String[] projection = {
            MediaStore.Images.Media._ID,
            MediaStore.Images.Media.DISPLAY_NAME,
            MediaStore.Images.Media.MIME_TYPE,
            MediaStore.Images.Media.SIZE,
            MediaStore.Images.Media.DATE_TAKEN,
            MediaStore.Images.Media.DATE_ADDED,
            MediaStore.Images.Media.DATE_MODIFIED,
            MediaStore.Images.Media.WIDTH,
            MediaStore.Images.Media.HEIGHT
        };
        JSArray assets = new JSArray();
        int total = 0;
        try (Cursor cursor = getContext().getContentResolver().query(
            imagesUri(), projection, null, null, MediaStore.Images.Media.DATE_ADDED + " DESC"
        )) {
            if (cursor != null) {
                total = cursor.getCount();
                if (offset < total) cursor.moveToPosition(offset - 1);
                int collected = 0;
                while (collected < limit && cursor.moveToNext()) {
                    long id = cursor.getLong(cursor.getColumnIndexOrThrow(MediaStore.Images.Media._ID));
                    Uri uri = ContentUris.withAppendedId(imagesUri(), id);
                    JSObject asset = new JSObject();
                    asset.put("id", "image:" + id);
                    asset.put("fileName", stringValue(cursor, MediaStore.Images.Media.DISPLAY_NAME, "image:" + id));
                    asset.put("type", "image");
                    asset.put("mimeType", stringValue(cursor, MediaStore.Images.Media.MIME_TYPE, "image/*"));
                    asset.put("size", longValue(cursor, MediaStore.Images.Media.SIZE));
                    asset.put("width", intValue(cursor, MediaStore.Images.Media.WIDTH));
                    asset.put("height", intValue(cursor, MediaStore.Images.Media.HEIGHT));
                    long taken = longValue(cursor, MediaStore.Images.Media.DATE_TAKEN);
                    if (taken <= 0) taken = longValue(cursor, MediaStore.Images.Media.DATE_ADDED) * 1000L;
                    long modified = longValue(cursor, MediaStore.Images.Media.DATE_MODIFIED) * 1000L;
                    if (taken > 0) asset.put("creationDate", iso.format(Instant.ofEpochMilli(taken)));
                    if (modified > 0) asset.put("modificationDate", iso.format(Instant.ofEpochMilli(modified)));
                    File thumbnail = thumbnail(uri, id, thumbWidth, thumbHeight, quality);
                    if (thumbnail != null) asset.put("thumbnail", fileObject(thumbnail));
                    assets.put(asset);
                    collected++;
                }
            }
        }
        JSObject result = new JSObject();
        result.put("assets", assets);
        result.put("totalCount", total);
        result.put("hasMore", offset + assets.length() < total);
        result.put("authorization", authorizationState());
        return result;
    }

    private File thumbnail(Uri uri, long id, int width, int height, double quality) throws Exception {
        File directory = new File(getContext().getCacheDir(), "pocketPhotos/thumbnails");
        if (!directory.exists() && !directory.mkdirs()) throw new IllegalStateException("photo_thumbnail_cache_unavailable");
        int qualityPercent = (int) Math.round(quality * 100);
        File target = new File(directory, id + "_" + width + "x" + height + "_q" + qualityPercent + ".jpg");
        if (target.exists() && target.length() > 0) return target;
        Bitmap bitmap;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            bitmap = getContext().getContentResolver().loadThumbnail(uri, new Size(width, height), null);
        } else {
            bitmap = MediaStore.Images.Thumbnails.getThumbnail(
                getContext().getContentResolver(), id, MediaStore.Images.Thumbnails.MINI_KIND, null
            );
        }
        if (bitmap == null) return null;
        Bitmap scaled = bitmap;
        if (bitmap.getWidth() > width || bitmap.getHeight() > height) {
            float ratio = Math.min((float) width / bitmap.getWidth(), (float) height / bitmap.getHeight());
            scaled = Bitmap.createScaledBitmap(bitmap, Math.max(1, Math.round(bitmap.getWidth() * ratio)), Math.max(1, Math.round(bitmap.getHeight() * ratio)), true);
        }
        try (FileOutputStream output = new FileOutputStream(target)) {
            scaled.compress(Bitmap.CompressFormat.JPEG, qualityPercent, output);
        } finally {
            if (scaled != bitmap) scaled.recycle();
            bitmap.recycle();
        }
        return target;
    }

    private JSObject fileObject(File file) {
        JSObject result = new JSObject();
        result.put("path", file.getAbsolutePath());
        String localUrl = getBridge().getLocalUrl();
        result.put("webPath", localUrl == null || localUrl.isEmpty()
            ? Uri.fromFile(file).toString()
            : FileUtils.getPortablePath(getContext(), localUrl, Uri.fromFile(file)));
        result.put("mimeType", "image/jpeg");
        result.put("size", file.length());
        return result;
    }

    private JSObject authorizationResult() {
        JSObject result = new JSObject();
        result.put("state", authorizationState());
        return result;
    }

    private String authorizationState() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            if (ContextCompat.checkSelfPermission(getContext(), Manifest.permission.READ_MEDIA_IMAGES) == android.content.pm.PackageManager.PERMISSION_GRANTED) return "authorized";
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE
                && ContextCompat.checkSelfPermission(getContext(), Manifest.permission.READ_MEDIA_VISUAL_USER_SELECTED) == android.content.pm.PackageManager.PERMISSION_GRANTED) return "limited";
        } else if (getPermissionState("legacyImages") == PermissionState.GRANTED) return "authorized";
        boolean asked = getContext().getSharedPreferences("pocket-photo-library", 0).getBoolean("asked", false);
        return asked ? "denied" : "notDetermined";
    }

    private Uri imagesUri() {
        return Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q
            ? MediaStore.Images.Media.getContentUri(MediaStore.VOLUME_EXTERNAL)
            : MediaStore.Images.Media.EXTERNAL_CONTENT_URI;
    }

    private long longValue(Cursor cursor, String column) {
        int index = cursor.getColumnIndex(column);
        return index < 0 || cursor.isNull(index) ? 0 : cursor.getLong(index);
    }

    private int intValue(Cursor cursor, String column) {
        int index = cursor.getColumnIndex(column);
        return index < 0 || cursor.isNull(index) ? 0 : cursor.getInt(index);
    }

    private String stringValue(Cursor cursor, String column, String fallback) {
        int index = cursor.getColumnIndex(column);
        if (index < 0 || cursor.isNull(index)) return fallback;
        String value = cursor.getString(index);
        return value == null || value.isEmpty() ? fallback : value;
    }
}
