import type { SkillManifest, SkillScope, SkillTool } from './types';
import { QWEN4B_HEALTH_ASSET, QWEN4B_HEALTH_RELEASE, QWEN4B_HEALTH_REVISION } from '../../../../frost-agent/edge/qwen4bHealthRelease';

const RELEASED_AT = '2026-08-19T00:00:00+08:00';

interface ExternalHealthSkillOptions {
  id: string;
  name: string;
  description: string;
  target: string;
  scopes: SkillScope[];
  tools: SkillTool[];
  networkHosts?: string[];
  schemas: string[];
  policyId: string;
  checks: string[];
  suite: string;
  source: string;
  license: string;
}

function externalHealthSkill(options: ExternalHealthSkillOptions): SkillManifest {
  return {
    protocol: 'pocket-skill/v1',
    identity: {
      id: options.id,
      name: options.name,
      version: '1.0.0',
      author: 'Frost Health · OSS adaptation',
      description: options.description,
    },
    kind: 'markdown',
    entry: { target: options.target },
    runtime: {
      execution: 'declarative', runtime_min: '1.0.0', platforms: ['web', 'android-arm64'],
      base: { id: QWEN4B_HEALTH_ASSET, revision: QWEN4B_HEALTH_REVISION, sha256: QWEN4B_HEALTH_RELEASE.sha256 },
    },
    permissions: {
      scopes: options.scopes,
      tools: options.tools,
      network_hosts: options.networkHosts || [],
    },
    data: { schemas: ['frost-qwen-control/v1', ...options.schemas] },
    quality_gate: { policy_id: options.policyId, checks: options.checks },
    fallback: { order: ['rules', 'user-confirmation', 'stop'] },
    evaluation: { suite: options.suite, passed: true, score: 1, threshold: 1, tested_at: RELEASED_AT },
    distribution: { channel: 'builtin', manifest_url: '', uninstall_policy: 'remove-skill-assets-keep-private-data' },
    assets: [{
      id: QWEN4B_HEALTH_ASSET,
      role: 'model',
      media_type: 'application/vnd.modelscope.repository+json',
      bytes: QWEN4B_HEALTH_RELEASE.bytes,
      sha256: QWEN4B_HEALTH_RELEASE.sha256,
      url: QWEN4B_HEALTH_RELEASE.url,
      optional: true,
    }],
    provenance: { source: options.source, license: options.license, released_at: RELEASED_AT },
  };
}

export const EXTERNAL_HEALTH_SKILLS: SkillManifest[] = [
  externalHealthSkill({
    id: 'frost.running-coach',
    name: '跑步决策教练',
    description: '以个人 7/28/56 天基线、恢复信号与训练史生成可执行处方；Qwen3-4B 只负责综合和解释，强度上限、停止规则与处方校验由确定性规则执行。',
    target: 'frost-running-coach',
    scopes: ['health-data', 'wearables'],
    tools: ['health_query', 'wearable_query', 'readiness', 'prescription'],
    schemas: ['frost-athlete-context/v1', 'frost-training-prescription/v1'],
    policyId: 'frost.running-coach-safety-gate/v1',
    checks: [
      '数据不足时不伪造个人基线或给出高置信处方',
      '强结论至少需要两个相互支持的恢复信号',
      'red 只允许休息或恢复活动，yellow 最高为轻松强度',
      '处方必须包含停止规则、降级选项和下一检查点',
      'Qwen3-4B 不得覆盖确定性安全门的结果',
    ],
    suite: 'frost-running-coach-contract-v1',
    source: 'Adapted from https://github.com/liumy-qd/running-coach-skill@bae32cf1d7b33156cd074f449044d61668f0bcb2',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.healthsync',
    name: 'Apple Health 本地同步',
    description: '导入 Apple Health XML/ZIP，本地去重并查询睡眠、步数、HRV、心率与跑步指标；Qwen3-4B 只读归一化结果，不直接拼写 SQL。',
    target: 'frost-healthsync',
    scopes: ['health-data'],
    tools: ['health_query'],
    schemas: ['frost-health-provider/v1', 'health_event/v1'],
    policyId: 'frost.healthsync-readonly-gate/v1',
    checks: [
      '只处理用户明确选择的 Apple Health 导出文件',
      '重复导入必须幂等并保留原始来源',
      '步数与能量必须使用去重 total，睡眠必须按会话聚类',
      '缺失夜不得当作 0 小时睡眠',
      '面向 Frost 的查询接口只读，禁止 INSERT、UPDATE、DELETE、DROP 与 ALTER',
    ],
    suite: 'frost-healthsync-adapter-contract-v1',
    source: 'Adapted from https://github.com/BRO3886/healthsync@3fc3a3f4364d5a182a5d760652c03ff4cd9ed1b0',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.mediapipe-motion',
    name: 'MediaPipe 动作信号',
    description: '为 Her Motion 提供 33 点姿态信号、视频节流、置信度门和连续帧确认；原始画面留在本机，Qwen3-4B 只读已确认的结构化姿态事件。',
    target: 'frost-motion-vision',
    scopes: ['camera'],
    tools: ['pose'],
    schemas: ['frost-pose-signal/v1', 'pocket-skill-session/v1'],
    policyId: 'frost.mediapipe-motion-gate/v1',
    checks: [
      '摄像头必须由用户明确开启并持续显示状态',
      '推理循环必须节流且页面退出时释放相机与模型',
      '低可见度关键点不参与动作判定',
      '姿态确认需要连续帧一致，单帧不发出完成事件',
      '原始视频帧不写入 health_event/v1',
    ],
    suite: 'frost-mediapipe-her-motion-contract-v1',
    source: 'Reference adaptation from https://github.com/liuchiawei/agent-skills@f5a7853d0d7db66ff7956fbaf504365c7971007d; no upstream text copied',
    license: 'reference-only; upstream skill unlicensed',
  }),
  externalHealthSkill({
    id: 'frost.endurance-guard',
    name: '耐力训练校验器',
    description: '以确定性规则校验耐力训练处方、强度上限、负荷递增与证据链；作为 Running Coach 的安全内核，不由 Qwen3-4B 自行改写。',
    target: 'frost-endurance-guard',
    scopes: ['health-data'],
    tools: ['readiness', 'prescription'],
    schemas: ['frost-training-prescription/v1', 'frost-prescription-audit/v1'],
    policyId: 'frost.endurance-deterministic-gate/v1',
    checks: [
      '处方输入缺少单位、时间窗或个人阈值时必须停止校验',
      '所有负荷或强度调整必须记录触发依据',
      '一周内每个类别只修改一个进阶变量',
      '急性表现下降或全身恢复异常必须优先降级',
      '校验不通过时返回明确原因和保守备选，不自动修饰为通过',
    ],
    suite: 'frost-endurance-guard-contract-v1',
    source: 'Adapted from https://github.com/CrankAddict/section-11@e212351c7fecd2facd2ef2955dfd2b155157c27f',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.openfoodfacts',
    name: '包装食品查询',
    description: '通过条码或名称查询 Open Food Facts，返回品牌、每 100g 营养值与数据完整度；只用于包装食品支路，不代替中餐照片估份。',
    target: 'frost-openfoodfacts',
    scopes: ['network', 'public-sources'],
    tools: ['food_lookup'],
    networkHosts: ['world.openfoodfacts.org'],
    schemas: ['frost-packaged-food/v1'],
    policyId: 'frost.openfoodfacts-source-gate/v1',
    checks: [
      '有精确条码时优先条码查询，文本搜索不得自动选中商品',
      '营养值默认是每 100g，换算份量时必须有包装净含量或用户输入',
      '社区数据不完整时必须保留 unknown 与缺失字段',
      '来源、条码、查询时间与原始单位必须保留',
      '未经用户确认不得写入餐食记录',
    ],
    suite: 'frost-openfoodfacts-adapter-contract-v1',
    source: 'Adapted from https://github.com/emmekappa/openfoodfacts-cli@2db85a7d36f4bfaa63d5c6410b61df3dd6fbb361',
    license: 'MIT (package metadata)',
  }),
  externalHealthSkill({
    id: 'frost.garmin-readonly',
    name: 'Garmin 只读同步',
    description: '查询 Garmin 活动、睡眠、心率、HRV、训练状态和分段；Frost 只开放读取命令，不暴露上传、删除、体重写入或跳过确认的命令。',
    target: 'frost-garmin-readonly',
    scopes: ['network', 'health-data', 'wearables'],
    tools: ['wearable_query', 'health_query'],
    networkHosts: ['connect.garmin.com', 'connectapi.garmin.com'],
    schemas: ['frost-health-provider/v1', 'frost-activity-laps/v1'],
    policyId: 'frost.garmin-readonly-gate/v1',
    checks: [
      '命令只能来自显式读取白名单',
      '活动 upload、delete、weight log 与 --force 永久阻断',
      '凭据只交给本地 Garmin CLI 保存，不进入 Qwen 上下文',
      'GPX/FIT 只在用户指定活动详细分析时按需读取',
      '设备综合评分保留 provider 属性，不冒充原始生理测量',
    ],
    suite: 'frost-garmin-readonly-adapter-contract-v1',
    source: 'Adapted from https://github.com/eddmann/garmin-connect-cli@4bc35dabaf9c0791630542be75ffe5556ef7f1f6',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.cn-health-library',
    name: '中国食品与健康解析',
    description: '抽取 health-coach 中的中国食品库、Apple Health 字段解析与周报结构；不引入实验室诊断、处方药或减重药决策流程。',
    target: 'frost-cn-health-library',
    scopes: ['health-data'],
    tools: ['food_lookup', 'health_query'],
    schemas: ['frost-cn-food/v1', 'frost-weekly-health-report/v1'],
    policyId: 'frost.cn-health-library-gate/v1',
    checks: [
      '食品数据优先保留包装标签或上游来源',
      '菜品热量是范围估算，不伪造精确克重',
      'Apple Health 字段只用于归一化，不重复实现 healthsync 的去重引擎',
      '周报只引用已确认事件并列出 source_event_ids',
      '医学检验诊断、补充剂互作用和减重药处方不在本 Skill 范围',
    ],
    suite: 'frost-cn-health-library-contract-v1',
    source: 'Selected adaptation from https://github.com/H1an1/health-coach@9c2da9483eb826d0ff4b42cb96f79e1218071215',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.outdoor-window',
    name: '户外运动窗口',
    description: '读取实时天气、AQI、紫外线、降雨与雷暴风险，用确定性规则给出今天适合跑步、散步还是室内训练的时间窗口；无需账号或 API Key。',
    target: 'frost-outdoor-window',
    scopes: ['location', 'network', 'public-sources'],
    tools: ['geocode', 'weather_lookup', 'readiness'],
    networkHosts: ['geocoding-api.open-meteo.com', 'api.open-meteo.com', 'air-quality-api.open-meteo.com'],
    schemas: ['frost-outdoor-window/v1'],
    policyId: 'frost.outdoor-window-gate/v1',
    checks: [
      '位置只能由用户输入或明确授权，不默认读取精确定位',
      'AQI、UV、降水与雷暴分别保留来源时间，不伪造实时值',
      '高温、严寒、严重空气污染或雷暴时只给室内备选',
      '建议必须包含补水、防晒或能见度相关的具体提醒',
      '天气数据只用于生活与运动安排，不构成医疗建议',
    ],
    suite: 'frost-outdoor-window-contract-v1',
    source: 'Adapted from https://github.com/weather-mcp/weather-mcp@37b0ddfcc681d2eece4dd1bf3eab3b194751e879',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.strava-replay',
    name: 'Strava 训练回放',
    description: '以只读方式导入 Strava 活动摘要、配速与分段，在本机复盘跑步、骑行和游泳；默认移除起终点与精确 GPS。',
    target: 'frost-strava-replay',
    scopes: ['network', 'health-data', 'wearables'],
    tools: ['wearable_query', 'activity_import', 'prescription'],
    networkHosts: ['www.strava.com', 'api.strava.com'],
    schemas: ['frost-strava-activity/v1', 'frost-activity-laps/v1'],
    policyId: 'frost.strava-replay-gate/v1',
    checks: [
      '只开放活动与训练历史读取，不创建、修改或删除 Strava 内容',
      'OAuth 凭据由本地连接器保存，不进入 Qwen 上下文',
      '精确 GPS、家庭起点和常用路线默认从摘要中移除',
      '配速与分段必须保留单位、活动 ID 和来源时间',
      '训练建议必须经过现有 readiness 与耐力校验器复核',
    ],
    suite: 'frost-strava-replay-contract-v1',
    source: 'Adapted from https://github.com/davidmosiah/strava-mcp@381c6fcac16cb732bfe53dc154161f4d9c3b7e66',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.sleep-detective',
    name: '睡眠侦探',
    description: '把睡眠、readiness 与咖啡、饮酒、晚间训练等自愿记录放在本机做趋势对比，明确区分相关性、样本不足与因果结论。',
    target: 'frost-sleep-detective',
    scopes: ['health-data', 'wearables'],
    tools: ['health_query', 'wearable_query', 'sleep_analysis'],
    schemas: ['frost-sleep-observation/v1'],
    policyId: 'frost.sleep-detective-gate/v1',
    checks: [
      '只有用户主动记录的咖啡、饮酒和训练标签可以参与分析',
      '少于七晚时必须标记样本不足且不输出趋势结论',
      '相关性不得表述为因果，混杂因素必须可见',
      '原始睡眠与生活标签默认只保存在本机',
      '持续严重失眠或危险症状只提示寻求专业帮助，不作诊断',
    ],
    suite: 'frost-sleep-detective-contract-v1',
    source: 'Adapted from https://github.com/FelixWag/oura-ring-mcp@01b59d2ef5e8b7956cc33d1a27997bb9cb482dde',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.meal-lens',
    name: '中国饮食镜头',
    description: '把餐食照片与用户确认的菜名、份量结合，查询中国食品参考库并输出热量与宏量营养范围；没有确认前不写入饮食记录。',
    target: 'frost-meal-lens',
    scopes: ['photos', 'health-data'],
    tools: ['vision', 'food_lookup'],
    schemas: ['frost-meal-observation/v1', 'health_event/v1'],
    policyId: 'frost.meal-lens-gate/v1',
    checks: [
      '照片只用于本次本地观察且不自动上传',
      '模型候选菜名必须由用户确认或修正',
      '无法称重时只给份量与营养范围，不伪造精确数值',
      '包装食品优先使用营养标签，餐馆菜品保留估算标记',
      '未经确认不得写入 meal_confirmed 事件',
    ],
    suite: 'frost-meal-lens-contract-v1',
    source: 'Selected adaptation from https://github.com/H1an1/health-coach@9c2da9483eb826d0ff4b42cb96f79e1218071215',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.wger-planner',
    name: 'wger 训练计划',
    description: '连接 wger 的训练、动作与进度数据，把选中的训练计划交给 Frost 编排；默认只读，开始训练或写回完成记录前必须由用户确认。',
    target: 'frost-wger-planner',
    scopes: ['network', 'health-data'],
    tools: ['prescription', 'health_query'],
    networkHosts: ['wger.de'],
    schemas: ['frost-workout-plan/v1', 'health_event/v1'],
    policyId: 'frost.wger-planner-gate/v1',
    checks: [
      '未连接 wger 时只显示能力与连接状态，不伪造训练计划',
      '账号令牌不得进入 Qwen 上下文或健康记忆',
      '导入计划默认只读，开始训练与写回完成记录必须确认',
      '训练强度必须经过 Frost readiness 与停止规则复核',
      '只把已确认的完成结果写入 health_event/v1',
    ],
    suite: 'frost-wger-planner-contract-v1',
    source: 'API adapter contract for https://github.com/wger-project/wger; no upstream code bundled',
    license: 'AGPL-3.0 (upstream service); adapter contract only',
  }),
  externalHealthSkill({
    id: 'frost.mealie-kitchen',
    name: 'Mealie 恢复厨房',
    description: '连接用户自己的 Mealie 食谱与餐食计划，为训练日和恢复日筛选可执行的一餐；创建计划或购物清单前必须确认。',
    target: 'frost-mealie-kitchen',
    scopes: ['network', 'health-data'],
    tools: ['food_lookup', 'health_query'],
    schemas: ['frost-recovery-meal/v1', 'health_event/v1'],
    policyId: 'frost.mealie-kitchen-gate/v1',
    checks: [
      '未连接用户自己的 Mealie 服务时只显示能力与连接状态，不伪造食谱',
      '服务地址与令牌只保存在本地连接器，不进入 Qwen 上下文',
      '筛选结果必须保留原食谱 ID、份量和来源',
      '创建餐食计划或购物清单属于写操作，必须由用户确认',
      '不把一般食谱建议表述为医疗营养处方',
    ],
    suite: 'frost-mealie-kitchen-contract-v1',
    source: 'API adapter contract for https://github.com/mealie-recipes/mealie; no upstream code bundled',
    license: 'AGPL-3.0 (upstream service); adapter contract only',
  }),
];
