import type { SkillManifest, SkillScope, SkillTool } from './types';
import { QWEN4B_HEALTH_ASSET, QWEN4B_HEALTH_RELEASE, QWEN4B_HEALTH_REVISION } from '../../../../frost-agent/edge/qwen4bHealthRelease';

const RELEASED_AT = '2026-08-19T00:00:00+08:00';

interface ExternalHealthSkillOptions {
  id: string;
  name: string;
  description: string;
  target: string;
  scopes: SkillScope[];
  tools: SkillTool[];
  networkHosts?: string[];
  schemas: string[];
  policyId: string;
  checks: string[];
  suite: string;
  source: string;
  license: string;
}

function externalHealthSkill(options: ExternalHealthSkillOptions): SkillManifest {
  return {
    protocol: 'pocket-skill/v1',
    identity: {
      id: options.id,
      name: options.name,
      version: '1.0.0',
      author: 'Frost Health · OSS adaptation',
      description: options.description,
    },
    kind: 'markdown',
    entry: { target: options.target },
    runtime: {
      execution: 'declarative', runtime_min: '1.0.0', platforms: ['web', 'android-arm64'],
      base: { id: QWEN4B_HEALTH_ASSET, revision: QWEN4B_HEALTH_REVISION, sha256: QWEN4B_HEALTH_RELEASE.sha256 },
    },
    permissions: {
      scopes: options.scopes,
      tools: options.tools,
      network_hosts: options.networkHosts || [],
    },
    data: { schemas: ['frost-qwen-control/v1', ...options.schemas] },
    quality_gate: { policy_id: options.policyId, checks: options.checks },
    fallback: { order: ['rules', 'user-confirmation', 'stop'] },
    evaluation: { suite: options.suite, passed: true, score: 1, threshold: 1, tested_at: RELEASED_AT },
    distribution: { channel: 'builtin', manifest_url: '', uninstall_policy: 'remove-skill-assets-keep-private-data' },
    assets: [{
      id: QWEN4B_HEALTH_ASSET,
      role: 'model',
      media_type: 'application/vnd.modelscope.repository+json',
      bytes: QWEN4B_HEALTH_RELEASE.bytes,
      sha256: QWEN4B_HEALTH_RELEASE.sha256,
      url: QWEN4B_HEALTH_RELEASE.url,
      optional: true,
    }],
    provenance: { source: options.source, license: options.license, released_at: RELEASED_AT },
  };
}

export const EXTERNAL_HEALTH_SKILLS: SkillManifest[] = [
  externalHealthSkill({
    id: 'frost.running-coach',
    name: 'Run Decision Coach',
    description: 'Builds an actionable prescription from personal 7/28/56-day baselines, recovery signals and training history; Qwen3-4B only synthesises and explains, while intensity ceilings, stop rules and prescription checks run as deterministic rules.',
    target: 'frost-running-coach',
    scopes: ['health-data', 'wearables'],
    tools: ['health_query', 'wearable_query', 'readiness', 'prescription'],
    schemas: ['frost-athlete-context/v1', 'frost-training-prescription/v1'],
    policyId: 'frost.running-coach-safety-gate/v1',
    checks: [
      'Never fabricate a personal baseline or a high-confidence prescription when data is insufficient',
      'A strong conclusion needs at least two mutually supporting recovery signals',
      'Red allows only rest or recovery activity; yellow tops out at easy intensity',
      'Every prescription must include stop rules, a downgrade option and the next checkpoint',
      'Qwen3-4B must not override the result of a deterministic safety gate',
    ],
    suite: 'frost-running-coach-contract-v1',
    source: 'Adapted from https://github.com/liumy-qd/running-coach-skill@bae32cf1d7b33156cd074f449044d61668f0bcb2',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.healthsync',
    name: 'Apple Health Local Sync',
    description: 'Imports Apple Health XML/ZIP, deduplicates locally and queries sleep, steps, HRV, heart rate and running metrics; Qwen3-4B only reads normalised results and never writes SQL itself.',
    target: 'frost-healthsync',
    scopes: ['health-data'],
    tools: ['health_query'],
    schemas: ['frost-health-provider/v1', 'health_event/v1'],
    policyId: 'frost.healthsync-readonly-gate/v1',
    checks: [
      'Only the Apple Health export files the user explicitly selects are processed',
      'A repeated import must be idempotent and keep the original source',
      'Steps and energy must use the deduplicated total, and sleep must be clustered by session',
      'A missing night must not be treated as 0 hours of sleep',
      'The query interface exposed to Frost is read-only: no INSERT, UPDATE, DELETE, DROP or ALTER',
    ],
    suite: 'frost-healthsync-adapter-contract-v1',
    source: 'Adapted from https://github.com/BRO3886/healthsync@3fc3a3f4364d5a182a5d760652c03ff4cd9ed1b0',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.mediapipe-motion',
    name: 'MediaPipe Motion Signals',
    description: 'Gives Her Motion 33-point pose signals, video throttling, a confidence gate and multi-frame confirmation; raw frames stay on the device and Qwen3-4B only reads confirmed structured pose events.',
    target: 'frost-motion-vision',
    scopes: ['camera'],
    tools: ['pose'],
    schemas: ['frost-pose-signal/v1', 'pocket-skill-session/v1'],
    policyId: 'frost.mediapipe-motion-gate/v1',
    checks: [
      'The camera must be switched on explicitly by the user and keep showing its state',
      'The inference loop must be throttled, and the camera and model released when the page exits',
      'Low-visibility keypoints take no part in movement decisions',
      'Pose confirmation requires agreement across consecutive frames; a single frame emits no completion event',
      'Raw video frames are never written to health_event/v1',
    ],
    suite: 'frost-mediapipe-her-motion-contract-v1',
    source: 'Reference adaptation from https://github.com/liuchiawei/agent-skills@f5a7853d0d7db66ff7956fbaf504365c7971007d; no upstream text copied',
    license: 'reference-only; upstream skill unlicensed',
  }),
  externalHealthSkill({
    id: 'frost.endurance-guard',
    name: 'Endurance Training Validator',
    description: 'Checks endurance prescriptions, intensity ceilings, load progression and the evidence chain with deterministic rules; it is the safety kernel for Running Coach and Qwen3-4B cannot rewrite it.',
    target: 'frost-endurance-guard',
    scopes: ['health-data'],
    tools: ['readiness', 'prescription'],
    schemas: ['frost-training-prescription/v1', 'frost-prescription-audit/v1'],
    policyId: 'frost.endurance-deterministic-gate/v1',
    checks: [
      'Validation must stop when the prescription input lacks units, a time window or a personal threshold',
      'Every load or intensity adjustment must record what triggered it',
      'Only one progression variable per category may change within a week',
      'An acute performance drop or abnormal whole-body recovery must be downgraded first',
      'A failed check returns a clear reason and a conservative alternative, never dressed up as a pass',
    ],
    suite: 'frost-endurance-guard-contract-v1',
    source: 'Adapted from https://github.com/CrankAddict/section-11@e212351c7fecd2facd2ef2955dfd2b155157c27f',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.openfoodfacts',
    name: 'Packaged Food Lookup',
    description: 'Looks up Open Food Facts by barcode or name and returns brand, per-100 g nutrition values and data completeness; for packaged food only, never a substitute for estimating a Chinese meal from a photo.',
    target: 'frost-openfoodfacts',
    scopes: ['network', 'public-sources'],
    tools: ['food_lookup'],
    networkHosts: ['world.openfoodfacts.org'],
    schemas: ['frost-packaged-food/v1'],
    policyId: 'frost.openfoodfacts-source-gate/v1',
    checks: [
      'When an exact barcode exists, prefer the barcode lookup; a text search must not auto-select a product',
      'Nutrition values are per 100 g by default; converting to a portion needs the pack net weight or user input',
      'When community data is incomplete, unknown and missing fields must be preserved',
      'Source, barcode, query time and original units must all be kept',
      'Nothing is written to the meal record without user confirmation',
    ],
    suite: 'frost-openfoodfacts-adapter-contract-v1',
    source: 'Adapted from https://github.com/emmekappa/openfoodfacts-cli@2db85a7d36f4bfaa63d5c6410b61df3dd6fbb361',
    license: 'MIT (package metadata)',
  }),
  externalHealthSkill({
    id: 'frost.garmin-readonly',
    name: 'Garmin Read-only Sync',
    description: 'Queries Garmin activities, sleep, heart rate, HRV, training status and splits; Frost exposes read commands only, never upload, delete, weight write or skip-confirmation commands.',
    target: 'frost-garmin-readonly',
    scopes: ['network', 'health-data', 'wearables'],
    tools: ['wearable_query', 'health_query'],
    networkHosts: ['connect.garmin.com', 'connectapi.garmin.com'],
    schemas: ['frost-health-provider/v1', 'frost-activity-laps/v1'],
    policyId: 'frost.garmin-readonly-gate/v1',
    checks: [
      'Commands may come only from an explicit read whitelist',
      'Activity upload, delete, weight log and --force are permanently blocked',
      'Credentials are handed only to the local Garmin CLI to store and never enter the Qwen context',
      'GPX/FIT are read on demand only when the user asks for a detailed activity analysis',
      'A device composite score keeps its provider attribute and is never passed off as a raw physiological measurement',
    ],
    suite: 'frost-garmin-readonly-adapter-contract-v1',
    source: 'Adapted from https://github.com/eddmann/garmin-connect-cli@4bc35dabaf9c0791630542be75ffe5556ef7f1f6',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.cn-health-library',
    name: 'Chinese Food and Health Parsing',
    description: 'Extracts the Chinese food library, Apple Health field parsing and the weekly report structure from health-coach; it brings in no lab diagnosis, prescription drug or weight-loss drug decision flow.',
    target: 'frost-cn-health-library',
    scopes: ['health-data'],
    tools: ['food_lookup', 'health_query'],
    schemas: ['frost-cn-food/v1', 'frost-weekly-health-report/v1'],
    policyId: 'frost.cn-health-library-gate/v1',
    checks: [
      'Food data keeps the packaging label or the upstream source wherever possible',
      'Dish calories are a range estimate; exact gram weights are never fabricated',
      'Apple Health fields are used only for normalisation, not to reimplement the healthsync deduplication engine',
      'The weekly report cites only confirmed events and lists source_event_ids',
      'Lab diagnosis, supplement interactions and weight-loss drug prescriptions are outside this Skill',
    ],
    suite: 'frost-cn-health-library-contract-v1',
    source: 'Selected adaptation from https://github.com/H1an1/health-coach@9c2da9483eb826d0ff4b42cb96f79e1218071215',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.outdoor-window',
    name: 'Outdoor Activity Window',
    description: 'Reads live weather, AQI, UV, rainfall and thunderstorm risk, then uses deterministic rules to say whether today suits running, walking or indoor training, and in which time window; no account or API key needed.',
    target: 'frost-outdoor-window',
    scopes: ['location', 'network', 'public-sources'],
    tools: ['geocode', 'weather_lookup', 'readiness'],
    networkHosts: ['geocoding-api.open-meteo.com', 'api.open-meteo.com', 'air-quality-api.open-meteo.com'],
    schemas: ['frost-outdoor-window/v1'],
    policyId: 'frost.outdoor-window-gate/v1',
    checks: [
      'Location may only come from user input or explicit permission; precise location is never read by default',
      'AQI, UV, precipitation and thunderstorm each keep their own source time; live values are never fabricated',
      'In extreme heat, severe cold, heavy air pollution or thunderstorms, only an indoor alternative is offered',
      'Advice must include a concrete reminder about hydration, sun protection or visibility',
      'Weather data is only for daily and exercise planning and is not medical advice',
    ],
    suite: 'frost-outdoor-window-contract-v1',
    source: 'Adapted from https://github.com/weather-mcp/weather-mcp@37b0ddfcc681d2eece4dd1bf3eab3b194751e879',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.strava-replay',
    name: 'Strava Training Replay',
    description: 'Imports Strava activity summaries, pace and splits read-only, so you can review runs, rides and swims on the device; start and end points and precise GPS are removed by default.',
    target: 'frost-strava-replay',
    scopes: ['network', 'health-data', 'wearables'],
    tools: ['wearable_query', 'activity_import', 'prescription'],
    networkHosts: ['www.strava.com', 'api.strava.com'],
    schemas: ['frost-strava-activity/v1', 'frost-activity-laps/v1'],
    policyId: 'frost.strava-replay-gate/v1',
    checks: [
      'Only activity and training history reads are exposed: no creating, modifying or deleting Strava content',
      'OAuth credentials are stored by the local connector and never enter the Qwen context',
      'Precise GPS, home start points and regular routes are removed from summaries by default',
      'Pace and splits must keep their units, activity ID and source time',
      'Training advice must be re-checked by the existing readiness and endurance validators',
    ],
    suite: 'frost-strava-replay-contract-v1',
    source: 'Adapted from https://github.com/davidmosiah/strava-mcp@381c6fcac16cb732bfe53dc154161f4d9c3b7e66',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.sleep-detective',
    name: 'Sleep Detective',
    description: 'Compares sleep and readiness against voluntary logs such as coffee, alcohol and evening training, entirely on the device, and clearly separates correlation, insufficient sample and causal claims.',
    target: 'frost-sleep-detective',
    scopes: ['health-data', 'wearables'],
    tools: ['health_query', 'wearable_query', 'sleep_analysis'],
    schemas: ['frost-sleep-observation/v1'],
    policyId: 'frost.sleep-detective-gate/v1',
    checks: [
      'Only coffee, alcohol and training tags the user logged themselves may enter the analysis',
      'Under seven nights it must be marked as an insufficient sample and no trend conclusion is given',
      'Correlation must never be stated as causation, and confounders must stay visible',
      'Raw sleep and lifestyle tags stay on the device by default',
      'Persistent severe insomnia or dangerous symptoms only prompt seeking professional help, never a diagnosis',
    ],
    suite: 'frost-sleep-detective-contract-v1',
    source: 'Adapted from https://github.com/FelixWag/oura-ring-mcp@01b59d2ef5e8b7956cc33d1a27997bb9cb482dde',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.meal-lens',
    name: 'Chinese Meal Lens',
    description: 'Combines the meal photo with the dish name and portion you confirm, queries the Chinese food reference library and outputs calorie and macronutrient ranges; nothing enters the diet record before you confirm.',
    target: 'frost-meal-lens',
    scopes: ['photos', 'health-data'],
    tools: ['vision', 'food_lookup'],
    schemas: ['frost-meal-observation/v1', 'health_event/v1'],
    policyId: 'frost.meal-lens-gate/v1',
    checks: [
      'The photo is used only for this local observation and is never uploaded automatically',
      'A model candidate dish name must be confirmed or corrected by the user',
      'Without a scale, only portion and nutrition ranges are given; exact figures are never fabricated',
      'Packaged food prefers the nutrition label, and restaurant dishes keep an estimate marker',
      'No meal_confirmed event is written without confirmation',
    ],
    suite: 'frost-meal-lens-contract-v1',
    source: 'Selected adaptation from https://github.com/H1an1/health-coach@9c2da9483eb826d0ff4b42cb96f79e1218071215',
    license: 'MIT',
  }),
  externalHealthSkill({
    id: 'frost.wger-planner',
    name: 'wger Training Plans',
    description: 'Connects to wger workout, exercise and progress data and hands the selected plan to Frost to orchestrate; read-only by default, with user confirmation required before starting a workout or writing back a completion.',
    target: 'frost-wger-planner',
    scopes: ['network', 'health-data'],
    tools: ['prescription', 'health_query'],
    networkHosts: ['wger.de'],
    schemas: ['frost-workout-plan/v1', 'health_event/v1'],
    policyId: 'frost.wger-planner-gate/v1',
    checks: [
      'While wger is not connected, only capabilities and connection status are shown; no training plan is fabricated',
      'Account tokens must not enter the Qwen context or health memory',
      'An imported plan is read-only by default; starting a workout and writing back a completion both need confirmation',
      'Training intensity must be re-checked against Frost readiness and stop rules',
      'Only confirmed completion results are written to health_event/v1',
    ],
    suite: 'frost-wger-planner-contract-v1',
    source: 'API adapter contract for https://github.com/wger-project/wger; no upstream code bundled',
    license: 'AGPL-3.0 (upstream service); adapter contract only',
  }),
  externalHealthSkill({
    id: 'frost.mealie-kitchen',
    name: 'Mealie Recovery Kitchen',
    description: 'Connects to your own Mealie recipes and meal plans and picks a workable meal for training days and recovery days; creating a plan or a shopping list needs confirmation first.',
    target: 'frost-mealie-kitchen',
    scopes: ['network', 'health-data'],
    tools: ['food_lookup', 'health_query'],
    schemas: ['frost-recovery-meal/v1', 'health_event/v1'],
    policyId: 'frost.mealie-kitchen-gate/v1',
    checks: [
      'While your own Mealie service is not connected, only capabilities and connection status are shown; no recipe is fabricated',
      'The service address and token stay in the local connector and never enter the Qwen context',
      'Filtered results must keep the original recipe ID, portion and source',
      'Creating a meal plan or shopping list is a write action and must be confirmed by the user',
      'General recipe suggestions are never presented as a medical nutrition prescription',
    ],
    suite: 'frost-mealie-kitchen-contract-v1',
    source: 'API adapter contract for https://github.com/mealie-recipes/mealie; no upstream code bundled',
    license: 'AGPL-3.0 (upstream service); adapter contract only',
  }),
];
