import { HEALTH_SKILL_PROTOCOL, type HealthSkillDefinition } from './contracts';

export const EXTERNAL_HEALTH_SKILL_DEFINITIONS: HealthSkillDefinition[] = [
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.running-coach',
    title: '跑步决策教练',
    description: '根据个人基线、恢复信号和训练史生成有上限的训练处方。',
    when_to_use: ['判断今天是否适合质量课', '生成跑步处方', '训练后复盘'],
    not_for: ['医疗诊断', '没有数据时伪造个人基线', '绕过停止规则'],
    eligibility: ['至少有两类恢复信号或明确降低置信度', '已排除紧急停止信号'],
    permissions: ['read:health_events', 'read:wearable', 'run:model', 'notify:user'],
    steps: [
      { id: 'baseline', tool: 'coach.assess-readiness', purpose: '计算个人基线偏离与 readiness 上限', requires_confirmation: false },
      { id: 'draft', tool: 'coach.draft-prescription', purpose: '由 Qwen3-4B 生成结构化处方草案', requires_confirmation: false },
      { id: 'validate', tool: 'coach.validate-prescription', purpose: '用确定性规则校验并必要时降级', requires_confirmation: false },
    ],
    stop_rules: ['胸痛、晕厥、异常呼吸或影响步态的疼痛立即 SAFE_STOP', 'red/yellow 上限不得被模型升级'],
    completion: ['输出数据置信度、证据窗、处方、停止规则、降级选项与下一检查点'],
    provenance: {
      version: '1.0.0', owner: 'Frost Health', license: 'MIT',
      source_url: 'https://github.com/liumy-qd/running-coach-skill', source_commit: 'bae32cf1d7b33156cd074f449044d61668f0bcb2',
      adaptation: 'Qwen3-4B control plane + deterministic readiness and prescription gates',
    },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.healthsync',
    title: 'Apple Health 本地同步',
    description: '导入 Apple Health 导出文件，去重并以只读方式查询睡眠、步数、HRV 与跑步指标。',
    when_to_use: ['导入 Apple Health XML/ZIP', '查询睡眠、步数、HRV 或跑步指标', '为教练建立个人基线'],
    not_for: ['直接修改 SQLite', '把缺失数据当作零', '将原始健康导出上传给模型'],
    eligibility: ['用户明确选择本地导出文件', '本地 healthsync 桥已可用'],
    permissions: ['read:local_files', 'read:health_events', 'write:health_events'],
    steps: [
      { id: 'import', tool: 'healthsync.import', purpose: '流式解析并幂等去重', requires_confirmation: true },
      { id: 'query', tool: 'healthsync.query', purpose: '通过白名单只读查询返回归一化结果', requires_confirmation: false },
    ],
    stop_rules: ['文件不是 HealthKit 导出时停止', '发现任何写 SQL 时阻断'],
    completion: ['导入记录包含来源 hash 与去重统计', '查询结果说明覆盖日期与缺失天数'],
    provenance: {
      version: '1.0.0', owner: 'Frost Health', license: 'MIT',
      source_url: 'https://github.com/BRO3886/healthsync', source_commit: '3fc3a3f4364d5a182a5d760652c03ff4cd9ed1b0',
      adaptation: 'Read-only bridge contract; upstream parser remains an optional local dependency',
    },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.mediapipe-motion',
    title: 'MediaPipe 动作信号',
    description: '在 Her Motion 内提供本地姿态关键点、节流、可见度门和连续帧确认。',
    when_to_use: ['动作陪伴', '姿态确认', '跑前热身'],
    not_for: ['从视频诊断伤病', '保存原始画面', '单帧判定动作完成'],
    eligibility: ['用户已同意开启摄像头', '安全预检未触发停止'],
    permissions: ['capture:camera', 'run:model', 'write:health_events'],
    steps: [
      { id: 'pose', tool: 'motion.pose-stream', purpose: '本地计算姿态关键点', requires_confirmation: true },
      { id: 'gate', tool: 'motion.confirm-pose', purpose: '连续帧与置信度门控', requires_confirmation: false },
    ],
    stop_rules: ['摄像头权限撤销或页面关闭时释放资源', '不确定时保持静默'],
    completion: ['只输出姿态 ID、置信度、连续帧数和会话 ID'],
    provenance: {
      version: '1.0.0', owner: 'Frost Health', license: 'reference-only; upstream skill unlicensed',
      source_url: 'https://github.com/liuchiawei/agent-skills/tree/main/skills/3d/mediapipe-usage', source_commit: 'f5a7853d0d7db66ff7956fbaf504365c7971007d',
      adaptation: 'Reference-only integration around the existing Her Motion runtime; no upstream text copied',
    },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.endurance-guard',
    title: '耐力训练校验器',
    description: '以确定性规则校验训练处方、负荷递增、恢复上限和审计证据。',
    when_to_use: ['发布训练处方前', '调整耐力训练负荷', '复核训练合规性'],
    not_for: ['用通用阈值代替个人基线', '让模型跳过规则', '自动发布训练计划'],
    eligibility: ['处方已结构化', '输入单位和时间窗明确'],
    permissions: ['read:health_events'],
    steps: [{ id: 'validate', tool: 'endurance.validate-prescription', purpose: '校验强度、时长、进阶变量与触发依据', requires_confirmation: false }],
    stop_rules: ['证据缺失或单位不明时不通过', '恢复上限冲突时返回保守方案'],
    completion: ['输出 pass/fail、规则 ID、触发依据与保守备选'],
    provenance: {
      version: '1.0.0', owner: 'Frost Health', license: 'MIT',
      source_url: 'https://github.com/CrankAddict/section-11', source_commit: 'e212351c7fecd2facd2ef2955dfd2b155157c27f',
      adaptation: 'Selected deterministic safety and audit rules; not a wholesale protocol import',
    },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.openfoodfacts',
    title: '包装食品查询',
    description: '通过条码或名称查询包装食品品牌、每 100g 营养值与数据完整度。',
    when_to_use: ['扫描包装食品条码', '查询品牌食品营养标签'],
    not_for: ['中餐照片估份', '在没有份量时计算整包热量', '把社区缺失字段补齐'],
    eligibility: ['有条码或明确商品名', '用户允许访问 Open Food Facts'],
    permissions: ['read:public_sources'],
    steps: [{ id: 'lookup', tool: 'food.off.lookup', purpose: '查询并归一化每 100g 营养字段', requires_confirmation: false }],
    stop_rules: ['文本搜索有多个候选时等待用户选择', '缺失值保留 unknown'],
    completion: ['返回条码、品名、品牌、每 100g 营养值、缺失字段和来源'],
    provenance: {
      version: '1.0.0', owner: 'Frost Health', license: 'MIT (package metadata)',
      source_url: 'https://github.com/emmekappa/openfoodfacts-cli', source_commit: '2db85a7d36f4bfaa63d5c6410b61df3dd6fbb361',
      adaptation: 'Network request and result contract only',
    },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.garmin-readonly',
    title: 'Garmin 只读同步',
    description: '只读查询 Garmin 活动、睡眠、HRV、心率、训练状态与分段。',
    when_to_use: ['同步 Garmin 近期训练', '查询 Garmin 恢复与训练状态', '获取指定活动分段'],
    not_for: ['上传或删除 Garmin 活动', '写入体重', '把账号凭据交给模型'],
    eligibility: ['本地 Garmin CLI 已授权', '命令在只读白名单内'],
    permissions: ['read:wearable', 'read:health_events'],
    steps: [{ id: 'query', tool: 'garmin.query-readonly', purpose: '调用结构化只读命令并标准化返回', requires_confirmation: false }],
    stop_rules: ['上传、删除、写入与 --force 命令立即阻断', '鉴权失效时等待用户在本地重新登录'],
    completion: ['返回 provider、覆盖日期、单位、原始活动 ID 和缺失字段'],
    provenance: {
      version: '1.0.0', owner: 'Frost Health', license: 'MIT',
      source_url: 'https://github.com/eddmann/garmin-connect-cli', source_commit: '4bc35dabaf9c0791630542be75ffe5556ef7f1f6',
      adaptation: 'Read-only command allowlist; destructive CLI surfaces intentionally excluded',
    },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.cn-health-library',
    title: '中国食品与健康解析',
    description: '为中餐、中国品牌食品、Apple Health 字段和周报结构提供本地参考层。',
    when_to_use: ['查询中国品牌食品', '估算中餐营养范围', '生成健康周报'],
    not_for: ['实验室诊断', '处方药或减重药决策', '替代 healthsync 去重引擎'],
    eligibility: ['食品有明确名称或品牌', '周报至少有一条已确认健康事件'],
    permissions: ['read:health_events'],
    steps: [
      { id: 'food', tool: 'food.cn.lookup', purpose: '查询中国食品参考值并保留范围', requires_confirmation: false },
      { id: 'report', tool: 'report.weekly-evidence', purpose: '仅根据已确认事件生成周报', requires_confirmation: false },
    ],
    stop_rules: ['无可追溯食品来源时只返回类别范围', '涉及诊断或处方药时退出本 Skill'],
    completion: ['食品结果带来源与范围', '周报包含 source_event_ids'],
    provenance: {
      version: '1.0.0', owner: 'Frost Health', license: 'MIT',
      source_url: 'https://github.com/H1an1/health-coach', source_commit: '9c2da9483eb826d0ff4b42cb96f79e1218071215',
      adaptation: 'Only Chinese food, Apple Health field interpretation and evidence-bound report structure selected',
    },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.outdoor-window',
    title: '户外运动窗口',
    description: '根据天气、空气质量、紫外线与雷暴风险安排户外运动或室内备选。',
    when_to_use: ['判断今天适不适合户外跑步', '选择低风险运动时间', '查看 AQI 与紫外线'],
    not_for: ['医疗诊断', '极端天气下鼓励户外训练', '未经同意读取精确位置'],
    eligibility: ['用户输入城市或授权位置', '公共天气数据可用'],
    permissions: ['read:location', 'read:public_sources'],
    steps: [
      { id: 'weather', tool: 'outdoor.fetch-conditions', purpose: '读取温度、降水、风、AQI、UV 与警报', requires_confirmation: false },
      { id: 'window', tool: 'outdoor.assess-window', purpose: '用确定性安全阈值选择运动方式', requires_confirmation: false },
    ],
    stop_rules: ['雷暴、严重空气污染或极端温度时只给室内备选', '数据过期时不声称实时'],
    completion: ['返回时间、来源、风险标签、运动建议与补水防晒提醒'],
    provenance: { version: '1.0.0', owner: 'Frost Health', license: 'MIT', source_url: 'https://github.com/weather-mcp/weather-mcp', source_commit: '37b0ddfcc681d2eece4dd1bf3eab3b194751e879', adaptation: 'Open-Meteo weather, AQI and UV contract with exercise-specific deterministic gates' },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.strava-replay',
    title: 'Strava 训练回放',
    description: '只读导入活动摘要与分段，在本机复盘训练且默认隐藏精确路线。',
    when_to_use: ['复盘一次 Strava 活动', '比较配速和分段', '回顾近期跑骑游训练'],
    not_for: ['写入或删除 Strava 活动', '默认展示精确 GPS', '绕过训练安全门'],
    eligibility: ['用户选择活动导出 JSON 或授权本地只读连接器'],
    permissions: ['read:local_files', 'read:wearable', 'read:health_events'],
    steps: [
      { id: 'import', tool: 'strava.import-readonly', purpose: '读取并去除敏感路线字段', requires_confirmation: true },
      { id: 'replay', tool: 'strava.replay', purpose: '生成配速、心率与分段复盘', requires_confirmation: false },
    ],
    stop_rules: ['文件格式不明时停止', '家庭起点或精确轨迹不得进入摘要'],
    completion: ['返回活动 ID、距离、时长、配速、分段与隐私处理说明'],
    provenance: { version: '1.0.0', owner: 'Frost Health', license: 'MIT', source_url: 'https://github.com/davidmosiah/strava-mcp', source_commit: '381c6fcac16cb732bfe53dc154161f4d9c3b7e66', adaptation: 'Local read-only activity replay and GPS-redacted summary contract' },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.sleep-detective',
    title: '睡眠侦探',
    description: '比较睡眠与咖啡、饮酒、晚间训练标签的趋势，同时拒绝把相关性写成因果。',
    when_to_use: ['分析睡眠波动', '记录咖啡或晚间训练', '寻找恢复趋势'],
    not_for: ['诊断睡眠疾病', '小样本得出因果结论', '自动读取未授权日记'],
    eligibility: ['用户主动输入或导入睡眠与生活标签'],
    permissions: ['read:health_events', 'read:wearable'],
    steps: [
      { id: 'log', tool: 'sleep.log-observation', purpose: '保存本地睡眠与生活标签', requires_confirmation: true },
      { id: 'compare', tool: 'sleep.compare-patterns', purpose: '按因素比较均值与样本量', requires_confirmation: false },
    ],
    stop_rules: ['少于七晚只显示记录，不输出趋势', '持续严重问题提示寻求专业帮助'],
    completion: ['返回样本量、分组差异、混杂因素与非因果声明'],
    provenance: { version: '1.0.0', owner: 'Frost Health', license: 'MIT', source_url: 'https://github.com/FelixWag/oura-ring-mcp', source_commit: '01b59d2ef5e8b7956cc33d1a27997bb9cb482dde', adaptation: 'Local annotations and trend comparison without causal claims' },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.meal-lens',
    title: '中国饮食镜头',
    description: '用照片与用户确认的菜名查询中国食品参考范围，确认前不写入饮食事实。',
    when_to_use: ['拍照记录一餐', '估算中餐份量范围', '确认菜名与营养信息'],
    not_for: ['仅凭照片断言精确克重', '医学营养处方', '未确认就写入记录'],
    eligibility: ['用户选择照片并允许本地处理'],
    permissions: ['read:local_files', 'read:health_events', 'write:health_events', 'run:model'],
    steps: [
      { id: 'observe', tool: 'meal.observe-local', purpose: '建立本地照片预览与菜名候选', requires_confirmation: true },
      { id: 'confirm', tool: 'meal.confirm-range', purpose: '查询参考库并确认份量范围', requires_confirmation: true },
    ],
    stop_rules: ['无法确认主要食物时保留 unknown', '原图不得自动上传'],
    completion: ['返回确认菜名、份量范围、营养范围、来源与估算标记'],
    provenance: { version: '1.0.0', owner: 'Frost Health', license: 'MIT', source_url: 'https://github.com/H1an1/health-coach', source_commit: '9c2da9483eb826d0ff4b42cb96f79e1218071215', adaptation: 'Chinese food references and confirmation-first meal workflow only' },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.wger-planner',
    title: 'wger 训练计划',
    description: '从 wger 读取训练计划、动作与进度，并在 Frost 安全门后开始或记录训练。',
    when_to_use: ['查看 wger 训练计划', '选择今天的力量训练', '记录训练完成情况'],
    not_for: ['未连接服务时伪造计划', '绕过 readiness 或停止规则', '未经确认写回训练结果'],
    eligibility: ['用户已连接 wger，或仅查看连接说明', '开始训练前已通过 Frost 安全检查'],
    permissions: ['read:health_events', 'write:health_events', 'read:public_sources'],
    steps: [
      { id: 'load', tool: 'wger.load-plan', purpose: '只读加载训练计划与动作来源', requires_confirmation: false },
      { id: 'review', tool: 'coach.validate-prescription', purpose: '按当天状态复核强度与停止规则', requires_confirmation: false },
      { id: 'complete', tool: 'wger.record-completion', purpose: '确认后记录完成结果', requires_confirmation: true },
    ],
    stop_rules: ['服务未连接或数据缺失时保持等待连接', '疼痛或危险症状触发 SAFE_STOP'],
    completion: ['输出来源计划、当天动作与安全调整', '确认后生成一次 workout 健康事实'],
    provenance: { version: '1.0.0', owner: 'Frost Health', license: 'AGPL-3.0 (upstream service)', source_url: 'https://github.com/wger-project/wger', adaptation: 'API adapter contract only; no upstream code bundled' },
  },
  {
    protocol: HEALTH_SKILL_PROTOCOL,
    skill_id: 'frost.mealie-kitchen',
    title: 'Mealie 恢复厨房',
    description: '从用户自己的 Mealie 食谱与餐食计划中筛选训练日或恢复日的一餐。',
    when_to_use: ['安排恢复餐', '从已有食谱选择训练日一餐', '准备购物清单'],
    not_for: ['医疗营养处方', '未连接服务时伪造食谱', '未经确认创建计划或购物清单'],
    eligibility: ['用户已连接自己的 Mealie，或仅查看连接说明'],
    permissions: ['read:health_events', 'read:public_sources'],
    steps: [
      { id: 'search', tool: 'mealie.search-recipes', purpose: '按训练与恢复目标只读筛选食谱', requires_confirmation: false },
      { id: 'plan', tool: 'mealie.create-meal-plan', purpose: '确认后加入餐食计划或购物清单', requires_confirmation: true },
    ],
    stop_rules: ['服务未连接或没有匹配食谱时保持等待连接', '过敏原和禁忌信息不完整时不自动选择'],
    completion: ['返回原食谱 ID、份量、来源与选择理由', '写操作仅在确认后执行'],
    provenance: { version: '1.0.0', owner: 'Frost Health', license: 'AGPL-3.0 (upstream service)', source_url: 'https://github.com/mealie-recipes/mealie', adaptation: 'API adapter contract only; no upstream code bundled' },
  },
];
