import { beforeEach, describe, expect, it, vi } from 'vitest';
import { enrichArtifact } from './tagging';

const mocks = vi.hoisted(() => ({
  enrichJSON: vi.fn(),
}));

vi.mock('../skills/enrichEntity', () => ({
  enrichJSON: mocks.enrichJSON,
}));

describe('enrichArtifact · Qwen 英文器类归一', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('将 Qwen 字符串置信度归一成可展示数值', async () => {
    mocks.enrichJSON.mockResolvedValueOnce({
      nameZh: '萨莫色雷斯胜利女神像',
      category: 'sculpture',
      culture: 'Ancient Greece',
      confidence: 'confidence 92%',
    });

    const result = await enrichArtifact('Winged Victory of Samothrace', 'Louvre label');

    expect(result.ok).toBe(true);
    expect(result.raw.category).toBe('造像');
    expect(result.raw.culture).toBe('古希腊');
    expect(result.raw.confidence).toBeCloseTo(0.92);
  });

  it('将 Qwen 带时代说明的英文文明短语归一到时间线文明字段', async () => {
    mocks.enrichJSON.mockResolvedValueOnce({
      nameZh: '萨莫色雷斯胜利女神像',
      category: 'sculpture',
      culture: 'Greek, Hellenistic period',
      confidence: 'confidence 88%',
    });

    const result = await enrichArtifact('Winged Victory of Samothrace', 'Louvre label');

    expect(result.ok).toBe(true);
    expect(result.raw.category).toBe('造像');
    expect(result.raw.culture).toBe('古希腊');
    expect(result.raw.confidence).toBeCloseTo(0.88);
  });

  it.each([
    ['ceramic ware', '陶器'],
    ['ceramic vase', '陶器'],
    ['earthenware cup', '陶器'],
    ['stoneware ewer', '陶器'],
    ['faience vessel', '陶器'],
    ['ceramic sherd', '陶器'],
    ['pottery sherd', '陶器'],
    ['earthenware fragment', '陶器'],
    ['clay tablet', '陶器'],
    ['cuneiform tablet', '陶器'],
    ['ostracon', '陶器'],
    ['泥板文书', '陶器'],
    ['陶片', '陶器'],
    ['陶罐', '陶器'],
    ['porcelain bowl', '瓷器'],
    ['porcelain vase', '瓷器'],
    ['porcelain dish', '瓷器'],
    ['celadon bowl', '瓷器'],
    ['porcelain sherd', '瓷器'],
    ['celadon fragment', '瓷器'],
    ['瓷片', '瓷器'],
    ['青花瓷瓶', '瓷器'],
    ['jade ware', '玉器'],
    ['lacquerware', '漆木器'],
    ['inro', '漆木器'],
    ['inrō case', '漆木器'],
    ['goldwork', '金银器'],
    ['trophy', '金银器'],
    ['award cup', '金银器'],
    ['奖杯', '金银器'],
    ['bronze ritual vessel', '青铜器'],
    ['oracle bone inscription', '甲骨'],
    ['photograph', '书画'],
    ['photography', '书画'],
    ['photographic prints', '书画'],
    ['fresco', '书画'],
    ['mural', '书画'],
    ['wall painting', '书画'],
    ['watercolor', '书画'],
    ['gouache', '书画'],
    ['pastel', '书画'],
    ['pastel drawing', '书画'],
    ['charcoal drawing', '书画'],
    ['ink drawing', '书画'],
    ['phonograph record', '书画'],
    ['vinyl record', '书画'],
    ['record sleeve', '书画'],
    ['黑胶唱片', '书画'],
    ['壁画', '书画'],
    ['glass plate negative', '书画'],
    ['lantern slide', '书画'],
    ['photographic negative', '书画'],
    ['daguerreotype', '书画'],
    ['ambrotype', '书画'],
    ['tintype', '书画'],
    ['albumen print', '书画'],
    ['cyanotype', '书画'],
    ['contact sheet', '书画'],
    ['negative strip', '书画'],
    ['film negative', '书画'],
    ['35mm slide', '书画'],
    ['stereograph', '书画'],
    ['cabinet card', '书画'],
    ['carte-de-visite', '书画'],
    ['mosaic panel', '书画'],
    ['tile panel', '书画'],
    ['stained glass window', '书画'],
    ['printed ephemera', '书画'],
    ['exhibition poster', '书画'],
    ['broadside', '书画'],
    ['pamphlet', '书画'],
    ['invitation card', '书画'],
    ['trade card', '书画'],
    ['business card', '书画'],
    ['cigarette card', '书画'],
    ['greeting card', '书画'],
    ['holiday card', '书画'],
    ['christmas card', '书画'],
    ['postcard', '书画'],
    ['souvenir postcard', '书画'],
    ['请柬', '书画'],
    ['名片', '书画'],
    ['贺卡', '书画'],
    ['节日卡', '书画'],
    ['明信片', '书画'],
    ['calendar', '书画'],
    ['wall calendar', '书画'],
    ['almanac', '书画'],
    ['年历', '书画'],
    ['月份牌', '书画'],
    ['ticket stub', '书画'],
    ['ration coupon', '书画'],
    ['receipt', '书画'],
    ['票根', '书画'],
    ['粮票', '书画'],
    ['playbill', '书画'],
    ['theatre program', '书画'],
    ['restaurant menu', '书画'],
    ['postage stamp', '书画'],
    ['philatelic material', '书画'],
    ['first day cover', '书画'],
    ['envelope', '书画'],
    ['节目单', '书画'],
    ['菜单', '书画'],
    ['woodblock print', '书画'],
    ['ukiyo-e print', '书画'],
    ['photogravure', '书画'],
    ['collotype', '书画'],
    ['aquatint', '书画'],
    ['mezzotint', '书画'],
    ['drypoint', '书画'],
    ['monotype', '书画'],
    ['monoprint', '书画'],
    ['linocut', '书画'],
    ['woodcut', '书画'],
    ['lithograph', '书画'],
    ['etching', '书画'],
    ['engraving', '书画'],
    ['screenprint', '书画'],
    ['silkscreen', '书画'],
    ['silk screen print', '书画'],
    ['浮世绘', '书画'],
    ['fan', '书画'],
    ['folding fan', '书画'],
    ['hand fan', '书画'],
    ['fan leaf', '书画'],
    ['扇面', '书画'],
    ['shadow puppet', '书画'],
    ['皮影', '书画'],
    ['screen', '书画'],
    ['album leaf', '书画'],
    ['album leaves', '书画'],
    ['photograph album', '书画'],
    ['photo book', '书画'],
    ['photobook', '书画'],
    ['scrapbook', '书画'],
    ['autograph album', '书画'],
    ['摄影集', '书画'],
    ['照片书', '书画'],
    ['剪贴簿', '书画'],
    ['manuscript leaf', '书画'],
    ['folio', '书画'],
    ['papyrus scroll', '书画'],
    ['papyrus fragment', '书画'],
    ['bookbinding', '书画'],
    ['manuscript binding', '书画'],
    ['book cover', '书画'],
    ['古籍装帧', '书画'],
    ['手稿页', '书画'],
    ['册页', '书画'],
    ['musical score', '书画'],
    ['manuscript score', '书画'],
    ['sheet music', '书画'],
    ['songbook', '书画'],
    ['hymnal', '书画'],
    ['libretto', '书画'],
    ['libretti', '书画'],
    ['乐谱', '书画'],
    ['唱本', '书画'],
    ['phonograph record', '书画'],
    ['gramophone record', '书画'],
    ['vinyl record', '书画'],
    ['shellac record', '书画'],
    ['record sleeve', '书画'],
    ['黑胶唱片', '书画'],
    ['thangka', '书画'],
    ['唐卡', '书画'],
    ['painted icon', '书画'],
    ['altarpiece', '书画'],
    ['triptych', '书画'],
    ['map', '书画'],
    ['atlas', '书画'],
    ['cartographic material', '书画'],
    ['architectural plan', '书画'],
    ['blueprint', '书画'],
    ['rubbing', '书画'],
    ['stone rubbing', '书画'],
    ['拓片', '书画'],
    ['碑拓', '书画'],
    ['catalogue', '书画'],
    ['exhibition catalog', '书画'],
    ['auction catalogue', '书画'],
    ['展览图录', '书画'],
    ['playing card', '书画'],
    ['tarot cards', '书画'],
    ['game card', '书画'],
    ['扑克牌', '书画'],
    ['herbarium specimen', '书画'],
    ['botanical illustration', '书画'],
    ['botanical plate', '书画'],
    ['specimen sheet', '书画'],
    ['entomology drawer', '书画'],
    ['植物图谱', '书画'],
    ['pinned butterfly specimen tray', '书画'],
    ['numismatic object', '钱币'],
    ['medals', '钱币'],
    ['trade token', '钱币'],
    ['orders and decorations', '钱币'],
    ['military decoration', '钱币'],
    ['order badge', '钱币'],
    ['banknote', '钱币'],
    ['paper money', '钱币'],
    ['纸币', '钱币'],
    ['勋章', '钱币'],
    ['纪念章', '钱币'],
    ['figurine', '造像'],
    ['statuette', '造像'],
    ['portrait bust', '造像'],
    ['ritual mask', '造像'],
    ['能面', '造像'],
    ['伎乐面', '造像'],
    ['wood carving', '造像'],
    ['ivory carving', '造像'],
    ['bone carving', '造像'],
    ['carved figure', '造像'],
    ['plaster cast', '造像'],
    ['sculpture cast', '造像'],
    ['石膏像', '造像'],
    ['木雕', '造像'],
    ['牙雕', '造像'],
    ['陶塑', '造像'],
    ['泥塑', '造像'],
    ['彩塑', '造像'],
    ['terracotta figure', '造像'],
    ['clay tomb figure', '造像'],
    ['funerary figure', '造像'],
    ['ushabti', '造像'],
    ['shabti', '造像'],
    ['沙布提俑', '造像'],
    ['mammal skull specimen', '造像'],
    ['taxidermy mount', '造像'],
    ['陶俑', '造像'],
    ['汉代墓俑', '造像'],
    ['figure drawing', '书画'],
    ['court robe', '织绣'],
    ['Noh theatre costume', '织绣'],
    ['silk garment', '织绣'],
    ['kimono with cranes', '织绣'],
    ['vestment', '织绣'],
    ['ecclesiastical vestment', '织绣'],
    ['chasuble', '织绣'],
    ['dalmatic', '织绣'],
    ['liturgical stole', '织绣'],
    ['cope', '织绣'],
    ['法衣', '织绣'],
    ['祭服', '织绣'],
    ['shawl', '织绣'],
    ['embroidered sash', '织绣'],
    ['lace collar', '织绣'],
    ['sampler', '织绣'],
    ['围裙', '织绣'],
    ['quilt', '织绣'],
    ['coverlet', '织绣'],
    ['woven mat', '织绣'],
    ['reed mat', '织绣'],
    ['被面', '织绣'],
    ['草席', '织绣'],
    ['prayer rug', '织绣'],
    ['kilim fragment', '织绣'],
    ['地毯', '织绣'],
    ['footwear', '佩饰'],
    ['embroidered shoes', '佩饰'],
    ['lotus shoes', '佩饰'],
    ['moccasins', '佩饰'],
    ['sandals', '佩饰'],
    ['鞋履', '佩饰'],
    ['绣鞋', '佩饰'],
    ['musical instrument', '乐器'],
    ['pipa', '乐器'],
    ['古琴', '乐器'],
    ['flute', '乐器'],
    ['drum', '乐器'],
    ['gong', '乐器'],
    ['violin', '乐器'],
    ['笛', '乐器'],
    ['铜鼓', '乐器'],
    ['temple bell', '乐器'],
    ['chime bells', '乐器'],
    ['bianzhong', '乐器'],
    ['jewelry', '佩饰'],
    ['personal ornament', '佩饰'],
    ['bead necklace', '佩饰'],
    ['ear spool', '佩饰'],
    ['ear flare', '佩饰'],
    ['amulet', '佩饰'],
    ['torc', '佩饰'],
    ['armlet', '佩饰'],
    ['anklet', '佩饰'],
    ['belt buckle', '佩饰'],
    ['hairpin', '佩饰'],
    ['hair comb', '佩饰'],
    ['belt hook', '佩饰'],
    ['fibula', '佩饰'],
    ['headdress', '佩饰'],
    ['ceremonial crown', '佩饰'],
    ['ritual hat', '佩饰'],
    ['头饰', '佩饰'],
    ['王冠', '佩饰'],
    ['发簪', '佩饰'],
    ['带钩', '佩饰'],
    ['臂环', '佩饰'],
    ['带扣', '佩饰'],
    ['badge', '佩饰'],
    ['lapel badge', '佩饰'],
    ['button badge', '佩饰'],
    ['campaign button', '佩饰'],
    ['insignia', '佩饰'],
    ['royal regalia', '佩饰'],
    ['scepter', '佩饰'],
    ['权杖', '佩饰'],
    ['首饰', '佩饰'],
    ['耳饰', '佩饰'],
    ['耳珰', '佩饰'],
    ['珠串', '佩饰'],
    ['徽章', '佩饰'],
    ['纽扣', '佩饰'],
    ['netsuke', '佩饰'],
    ['ojime bead', '佩饰'],
    ['cameo', '佩饰'],
    ['scarab amulet', '佩饰'],
    ['cylinder seal', '印章'],
    ['seal', '印章'],
    ['seal stamp', '印章'],
    ['stamp seal', '印章'],
    ['seal matrix', '印章'],
    ['intaglio', '印章'],
    ['scarab seal', '印章'],
    ['印玺', '印章'],
    ['玉印', '印章'],
    ['box', '容器'],
    ['casket', '容器'],
    ['reliquary', '容器'],
    ['vessel', '容器'],
    ['jar', '容器'],
    ['bowl', '容器'],
    ['vase', '容器'],
    ['ewer', '容器'],
    ['chalice', '容器'],
    ['goblet', '容器'],
    ['censer', '容器'],
    ['incense burner', '容器'],
    ['basket', '容器'],
    ['woven basket', '容器'],
    ['basketry tray', '容器'],
    ['coiled basket', '容器'],
    ['wicker basket', '容器'],
    ['splint basket', '容器'],
    ['snuff bottle', '容器'],
    ['snuff box', '容器'],
    ['writing box', '容器'],
    ['brush pot', '容器'],
    ['brush washer', '容器'],
    ['water dropper', '容器'],
    ['笔筒', '容器'],
    ['笔洗', '容器'],
    ['香炉', '容器'],
    ['竹篮', '容器'],
    ['香盒', '容器'],
    ['经盒', '容器'],
    ['glassware', '容器'],
    ['glass ware', '容器'],
    ['玻璃器', '容器'],
    ['琉璃器', '容器'],
    ['sarcophagus', '棺椁'],
    ['coffin', '棺椁'],
    ['mummy case', '棺椁'],
    ['mummy', '棺椁'],
    ['mummified remains', '棺椁'],
    ['石棺', '棺椁'],
    ['木乃伊棺', '棺椁'],
    ['木乃伊', '棺椁'],
    ['armor', '甲胄'],
    ['suit of armour', '甲胄'],
    ['helmet', '甲胄'],
    ['ceremonial helmet', '甲胄'],
    ['kabuto', '甲胄'],
    ['头盔', '甲胄'],
    ['arms and armour', '兵器'],
    ['sword', '兵器'],
    ['dagger', '兵器'],
    ['spearhead', '兵器'],
    ['shield', '兵器'],
    ['firearm', '兵器'],
    ['musket', '兵器'],
    ['火枪', '兵器'],
    ['刀剑', '兵器'],
    ['architectural model', '模型'],
    ['museum diorama', '模型'],
    ['maquette', '模型'],
    ['沙盘', '模型'],
    ['船模', '模型'],
    ['carriage', '交通工具'],
    ['ceremonial chariot', '交通工具'],
    ['boat', '交通工具'],
    ['ship', '交通工具'],
    ['车马', '交通工具'],
    ['installation art', '装置'],
    ['immersive installation', '装置'],
    ['site-specific installation', '装置'],
    ['装置艺术', '装置'],
    ['clock', '仪器'],
    ['pocket watch', '仪器'],
    ['astrolabe', '仪器'],
    ['scientific instrument', '仪器'],
    ['camera', '仪器'],
    ['film projector', '仪器'],
    ['photographic lens', '仪器'],
    ['magic lantern', '仪器'],
    ['天球仪', '仪器'],
    ['architectural fragment', '石刻'],
    ['column capital', '石刻'],
    ['bas-relief panel', '石刻'],
    ['frieze fragment', '石刻'],
    ['inscribed stone plaque', '石刻'],
    ['stone tablet', '石刻'],
    ['memorial plaque', '石刻'],
    ['commemorative plaque', '石刻'],
    ['throne', '家具'],
    ['table', '家具'],
    ['bed', '家具'],
    ['wardrobe', '家具'],
    ['newspaper clipping', '书画'],
    ['periodical', '书画'],
    ['correspondence', '书画'],
    ['剪报', '书画'],
    ['natural history specimen', '标本'],
    ['meteorite fragment', '标本'],
    ['mineral specimen', '标本'],
    ['moon rock fragment', '标本'],
    ['quartz crystal', '标本'],
    ['coral specimen', '标本'],
    ['marine shell specimen', '标本'],
    ['conch shell', '标本'],
    ['wet specimen jar', '标本'],
    ['fluid-preserved specimen', '标本'],
    ['formalin-preserved fish specimen', '标本'],
    ['fossil bone', '标本'],
    ['dinosaur egg', '标本'],
    ['amber inclusion', '标本'],
    ['液浸标本', '标本'],
    ['珊瑚标本', '标本'],
    ['化石骨', '标本'],
    ['琥珀包裹体', '标本'],
    ['key', '工具'],
    ['door key', '工具'],
    ['padlock', '工具'],
    ['钥匙', '工具'],
    ['挂锁', '工具'],
    ['toy', '玩具'],
    ['doll', '玩具'],
    ['puppet', '玩具'],
    ['game piece', '玩具'],
    ['dice', '玩具'],
    ['木偶', '玩具'],
    ['棋子', '玩具'],
    ['smoking pipe', '烟具'],
    ['tobacco pipe', '烟具'],
    ['hookah', '烟具'],
    ['烟斗', '烟具'],
    ['oil lamp', '灯具'],
    ['mosque lamp', '灯具'],
    ['candlestick', '灯具'],
    ['candelabrum', '灯具'],
    ['烛台', '灯具'],
  ])('将 %s 归一成 %s', async (category, expected) => {
    mocks.enrichJSON.mockResolvedValueOnce({
      nameZh: '测试展品',
      category,
      culture: 'Ancient China',
    });

    const result = await enrichArtifact('测试展品', category);

    expect(result.ok).toBe(true);
    expect(result.raw.category).toBe(expected);
  });
});
